### ISSUE TITLE
DDNS问题

### ISSUE THREAD

**Issue by dsus4wang** [Dustella/i-NUIST-login-golang#1]
学校有办法获取到公网ip吗？不太理解ddns的意义

**Comment by Dustella** [comment]
这是为了学校的大内网内通信用的

假设你在学校里面有若干跑着的服务器，上面使用`cron`挂着这个程序登录
在各种断网和重连过后 校内的IP往往会变化
这个 DDNS 只是为了绑定机器在大内网里面那个`10.`开头的地址
在校内服务器断线重连过后，我在校园网内可以用这个IP访问到自己的机器

**Comment by dsus4wang** [comment]
谢谢解答，我记得我刚入学的时候，发现学校内网做了AP隔离，现在是解除了吗？

**Comment by Dustella** [comment]
> 谢谢解答，我记得我刚入学的时候，发现学校内网做了AP隔离，现在是解除了吗？

大内网内一直没有 AP 隔离。

[NUISTCraft](https://nuistcraft.com) 二周目曾经开在学校内网内，若干组织的 nas 也直接架设在内网里。

但是需要注意，内网内的 UDP 链接不稳，但是 TCP 没问题
